#**E03 Leitura de dados**
Grupo 5

Yuri Oliveira Alves, Bruno Schuster, Victor Klafke, Marcos André Debona

### Objetivos Atingidos:
- [x] Faz upload do arquivo local?
- [x] Lê todas as linhas?
- [x] Remove cabeçalho (primeira linha)?
- [x] Mostra o número total de linhas?
- [x] Decodifica as linhas para string simples?
- [x] Remove '\n' do final de cada linha?
- [x] Separa os dados de cada linha usando vírgula como espaçador?
- [x] Cria uma array do NumPy com todos dados de entrada no formato ponto flutuante?
- [x] Cria outro array do NumPy com as saídas no formato one-hot?
- [x] Encontra o maior e o menor valor para cada coluna do array de entradas?
- [x] Normaliza o array de entradas para que todos valores estejam no intervalo de 0 a 1?
- [x] O valor mínimo corresponde ao zero e o valor máximo corresponde a 1 para cada coluna?
- [x] Embaralha as linhas das entradas e das saídas, mantendo os pares correspondentes?
- [x] Separa dados de treinamento e validação na proporção 90%/10%?
- [x] O código está documentado com comentários mostrando exatamente onde se cumpre cada um dos requisitos acima?
- [x] Há células de texto, identificando o grupo, seus membros e explicando cada etapa do código?


####DEFINIÇÃO DE MÓDULOS

In [2]:
#Importação das bibliotecas necessárias
import io
import numpy as np
import random
from google.colab import files

####CARGA DATASET

Aqui fazemos upload do dataset e carregamos ele na memoria


In [3]:
#Remove todos arquivos do tipo .csv
!rm -f *.csv

In [4]:
#Importação do dataset
d = files.upload()

Saving Iris.csv to Iris.csv


In [5]:
#Print do dataset 
print(d)

{'Iris.csv': b'Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n1,5.1,3.5,1.4,0.2,Iris-setosa\n2,4.9,3.0,1.4,0.2,Iris-setosa\n3,4.7,3.2,1.3,0.2,Iris-setosa\n4,4.6,3.1,1.5,0.2,Iris-setosa\n5,5.0,3.6,1.4,0.2,Iris-setosa\n6,5.4,3.9,1.7,0.4,Iris-setosa\n7,4.6,3.4,1.4,0.3,Iris-setosa\n8,5.0,3.4,1.5,0.2,Iris-setosa\n9,4.4,2.9,1.4,0.2,Iris-setosa\n10,4.9,3.1,1.5,0.1,Iris-setosa\n11,5.4,3.7,1.5,0.2,Iris-setosa\n12,4.8,3.4,1.6,0.2,Iris-setosa\n13,4.8,3.0,1.4,0.1,Iris-setosa\n14,4.3,3.0,1.1,0.1,Iris-setosa\n15,5.8,4.0,1.2,0.2,Iris-setosa\n16,5.7,4.4,1.5,0.4,Iris-setosa\n17,5.4,3.9,1.3,0.4,Iris-setosa\n18,5.1,3.5,1.4,0.3,Iris-setosa\n19,5.7,3.8,1.7,0.3,Iris-setosa\n20,5.1,3.8,1.5,0.3,Iris-setosa\n21,5.4,3.4,1.7,0.2,Iris-setosa\n22,5.1,3.7,1.5,0.4,Iris-setosa\n23,4.6,3.6,1.0,0.2,Iris-setosa\n24,5.1,3.3,1.7,0.5,Iris-setosa\n25,4.8,3.4,1.9,0.2,Iris-setosa\n26,5.0,3.0,1.6,0.2,Iris-setosa\n27,5.0,3.4,1.6,0.4,Iris-setosa\n28,5.2,3.5,1.5,0.2,Iris-setosa\n29,5.2,3.4,1.4,0.2,Iris-setosa\n

In [6]:
#Carrega p/ MEM
f = io.BytesIO(d[list(d.items())[0][0]])

####ETAPA DE PROCESSAMENTO E ANÁLISE DOS DADOS 

Aqui fazemos a limpeza e processamento do dataset, na ordem: 

                                            -Leitura de todas as linhas
                                            -Remoção do cabeçalho
                                            -Remoção do newline de cada linha
                                            -Adiciona linhas decodificadas a um array (data)
                                            -Printa o datased decodificado sem cabeçalho
                                            -Printa o numero de linhas do dataset
                                            -Criamos um novo array com os dados separados por ','
                                            -Criamos um novo array sem os dados de ID e saida (fdata)
                                            -Criamos um array do numpy com os dados (nparray)
                                            -Criamos o array de saidas no formato one_hot
                                            -Populamos o array one_hot com as saidas
                                            -Printa o array de entradas
                                            -Printa o array de saidas
                                            -Encontra e armazena os valores min/max das entradas
                                            -Normaliza o array entre 0 - 1
                                            -Printa o min/max do array normalizado
                                            -Printa o array normalizado


In [7]:
#Retorna o ponteiro de leitura sempre para o inicio do arquivo
f.seek(0) 

#Leitura de todas as linhas 
lines = f.readlines()

#Criação de um array vazio
data = []

#For percorrendo as linhas 
for line in lines[1:]: #[1:] "pula" a primeira linha
  data.append(line.decode()[:-1]) #adiciona a linha decoficada, removendo o \n ([:-1] )

#Printa o dataset decodificado sem o cabeçalho
print(data)

#Printa o numero de linhas do dataset
print(len(data))

#Separação dos dados de cada linha utilizando o delimitador "," 
splitData = [str.split(",") for str in data]

#Gerado um novo dataset, "ignorando" a primeira e a ultima coluna
#Já que a primeira coluna são os ID's e a Ultima são as classes
fData = [x[1:5] for x in splitData]

#Criação de um array do numpay, definindo os dados como ponto flutuante
nparray = np.array(fData,dtype="float")

#Array de zeros, a ser preenchido com as saidas do one-hot
one_hot = np.zeros((len(lines)-1,3))

#Define as possiveis categorias de saida para o one-hot
categ = np.array(['Iris-setosa','Iris-versicolor','Iris-virginica'])

#Cria o array com saidas one-hot
for line in range(len(data)):
  one_hot[line] = (categ == splitData[line][5]).astype('float')

#Printa o array one-hot
print(one_hot)

#Printa o array de entradas
print(nparray)

#Encontrando o maior valor para cada coluna (axis=0)
col0max, col1max, col2max, col3max = nparray.max(axis=0)

#Encontrando o menor valor para cada coluna (axis=0)
col0min, col1min, col2min, col3min = nparray.min(axis=0)


['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa', '7,4.6,3.4,1.4,0.3,Iris-setosa', '8,5.0,3.4,1.5,0.2,Iris-setosa', '9,4.4,2.9,1.4,0.2,Iris-setosa', '10,4.9,3.1,1.5,0.1,Iris-setosa', '11,5.4,3.7,1.5,0.2,Iris-setosa', '12,4.8,3.4,1.6,0.2,Iris-setosa', '13,4.8,3.0,1.4,0.1,Iris-setosa', '14,4.3,3.0,1.1,0.1,Iris-setosa', '15,5.8,4.0,1.2,0.2,Iris-setosa', '16,5.7,4.4,1.5,0.4,Iris-setosa', '17,5.4,3.9,1.3,0.4,Iris-setosa', '18,5.1,3.5,1.4,0.3,Iris-setosa', '19,5.7,3.8,1.7,0.3,Iris-setosa', '20,5.1,3.8,1.5,0.3,Iris-setosa', '21,5.4,3.4,1.7,0.2,Iris-setosa', '22,5.1,3.7,1.5,0.4,Iris-setosa', '23,4.6,3.6,1.0,0.2,Iris-setosa', '24,5.1,3.3,1.7,0.5,Iris-setosa', '25,4.8,3.4,1.9,0.2,Iris-setosa', '26,5.0,3.0,1.6,0.2,Iris-setosa', '27,5.0,3.4,1.6,0.4,Iris-setosa', '28,5.2,3.5,1.5,0.2,Iris-setosa', '29,5.2,3.4,1.4,0.2,Iris-setosa', '30,4.7,3.2,1.6,0.2,Ir

In [8]:
#Salva os valores de min e max globais
min = nparray.min()
max = nparray.max()

#Criação do array a ser utilizado na normalização
array_norm = np.empty_like(nparray)

#Realização da normalização, salvando o resultado no "array_norm"
# for i in range(len(nparray)):
#   for j in range(len(nparray[i])):
    #norm=(xi−min(x))/(max(x)−min(x))
array_norm= (nparray - min)/(max-min)

#Comprovando que os valores do array array_norm estão entre 0 e 1
print(array_norm.min(), array_norm.max())

#Print do array normalizado
print(array_norm)



0.0 1.0
[[0.64102564 0.43589744 0.16666667 0.01282051]
 [0.61538462 0.37179487 0.16666667 0.01282051]
 [0.58974359 0.3974359  0.15384615 0.01282051]
 [0.57692308 0.38461538 0.17948718 0.01282051]
 [0.62820513 0.44871795 0.16666667 0.01282051]
 [0.67948718 0.48717949 0.20512821 0.03846154]
 [0.57692308 0.42307692 0.16666667 0.02564103]
 [0.62820513 0.42307692 0.17948718 0.01282051]
 [0.55128205 0.35897436 0.16666667 0.01282051]
 [0.61538462 0.38461538 0.17948718 0.        ]
 [0.67948718 0.46153846 0.17948718 0.01282051]
 [0.6025641  0.42307692 0.19230769 0.01282051]
 [0.6025641  0.37179487 0.16666667 0.        ]
 [0.53846154 0.37179487 0.12820513 0.        ]
 [0.73076923 0.5        0.14102564 0.01282051]
 [0.71794872 0.55128205 0.17948718 0.03846154]
 [0.67948718 0.48717949 0.15384615 0.03846154]
 [0.64102564 0.43589744 0.16666667 0.02564103]
 [0.71794872 0.47435897 0.20512821 0.02564103]
 [0.64102564 0.47435897 0.17948718 0.02564103]
 [0.67948718 0.42307692 0.20512821 0.01282051]
 [0.6

####ETAPA DE SEPARAÇÃO FINAL

Aqui finalizamos o processamento do dataset, nos seguintes passos:
                                                                
                                                                -Embaralhamos as entradas e saidas, mantendo os pares
                                                                -Separamos em dados de treinamento e validação, na proporçao 90/10


In [9]:
#Embaralha entradas e saidas, mantendo os pares correspondentes
mapIndexPosition = list(zip(nparray, one_hot))

np.random.shuffle(mapIndexPosition)
nparray, one_hot = zip(*mapIndexPosition)

In [10]:
#Separação dos dados de treinamento e validação
p_treino = 0.90 # Porcentagem treino

treinoEntrada = nparray[:int((len(nparray))*p_treino)] #Gera um array com 90% do tamanho do dataset de entrada 
treinoSaida = one_hot[:int((len(one_hot))*p_treino)] # gera um array com 90% do tamanho do dataset de saida

validacaoEntrada = nparray[int((len(nparray))*p_treino):]  #Gera um array com 10% do tamanho do dataset de entrada
validacaoSaida = one_hot[int((len(one_hot))*p_treino):] # gera um array com 10% do tamanho do dataset de saida
